#!/bin/bash

SCRIPT=$( readlink -m $( type -p $0 ))
BASE_DIR=`dirname ${SCRIPT}`
NAME=`basename ${SCRIPT}`

GUNBOT=gunthy-linuxx64
EXCHANGE=poloniex
BASE="btc eth usdt xmr"

PAIRSTARTDELAY=10

YAML=$BASE_DIR/allpairs.yaml

GLOBALSTARTSCRIPT=gbstart
GLOBALSTOPSCRIPT=gbstop
GLOBALCLEARPM2SCRIPT=gbclear

echo "#!/bin/sh">$GLOBALSTOPSCRIPT
echo "#!/bin/sh">$GLOBALSTARTSCRIPT
echo "#!/bin/sh">$GLOBALCLEARPM2SCRIPT

BASEPATH=/opt

for base in $BASE; do
echo "cd $BASE_DIR">>$GLOBALSTARTSCRIPT



if [ "$EXCHANGE" = "poloniex" ] && [ "$base" = "btc" ]; then
   GUNBOTFLDR=gunbot
else
   GUNBOTFLDR=gunbot_${EXCHANGE}_${base}
fi

GUNBOTROOT=${BASEPATH}/${GUNBOTFLDR}

if [ ! -d "$GUNBOTROOT" ]; then
        mkdir $GUNBOTROOT
fi

if [ ! -d "/opt/gunbot_backup/${GUNBOTFLDR}" ]; then
        mkdir -p /opt/gunbot_backup/${GUNBOTFLDR}
    else
        cp -R --backup=t $GUNBOTROOT/* /opt/gunbot_backup/${GUNBOTFLDR}/
fi

if [ ! -d "$GUNBOTROOT/yaml" ]; then
        mkdir $GUNBOTROOT/yaml
fi

rm -f $GUNBOTROOT/yaml/*

cp $BASE_DIR/templates/ALLPAIRS-params.js $GUNBOTROOT

cd $BASE_DIR/

echo "apps:">$YAML

for pair in `cat $BASE_DIR/pairs/${EXCHANGE}_${base}| tr "\n" " "`; do

        echo "  - script : $GUNBOTROOT/gunthy-linuxx64">>$YAML
        echo "    name : '${EXCHANGE}-${pair}'">>$YAML
        echo "    args : ${pair} ${EXCHANGE}">>$YAML

        echo "apps:">$GUNBOTROOT/yaml/${EXCHANGE}-${pair}.yaml

        echo "  - script : $GUNBOTROOT/gunthy-linuxx64">>$GUNBOTROOT/yaml/${EXCHANGE}-${pair}.yaml
        echo "    name : '${EXCHANGE}-${pair}'">>$GUNBOTROOT/yaml/${EXCHANGE}-${pair}.yaml
        echo "    args : ${pair} ${EXCHANGE}">>$GUNBOTROOT/yaml/${EXCHANGE}-${pair}.yaml

        echo "pm2 start yaml/${EXCHANGE}-${pair}.yaml">>$GLOBALSTARTSCRIPT
        echo "sleep ${pair}STARTDELAY">>$GLOBALSTARTSCRIPT
        echo "pm2 stop ${EXCHANGE}-${pair}">>$GLOBALSTOPSCRIPT
        echo "pm2 delete ${EXCHANGE}-${pair}">>$GLOBALCLEARPM2SCRIPT

       cp --backup=t $BASE_DIR/templates/${EXCHANGE}-config-template.js $GUNBOTROOT/${EXCHANGE}-${pair}-config.js

done; done

echo "pm2 save">>$GLOBALSTARTSCRIPT

chmod +x $GLOBALSTARTSCRIPT
chmod +x $GLOBALSTOPSCRIPT
chmod +x $GLOBALCLEARPM2SCRIPT

ls -R ${BASEPATH}/gunbot*/

cd $BASE_DIR

